export enum ActivitySource {
  SCRIPT = 'system',
  SUPERADMIN = 'admin',
  SUBSCRIPTION = 'credits-subscription',
  PAY_AS_YOU_GO = 'credits-payg',
  VIDEO_GENERATION = 'video-generate',
  IMAGE_GENERATION = 'image-generate',
  MUSIC_GENERATION = 'music-generate',
  ARTICLE_GENERATION = 'article-generate',
  AVATAR_GENERATION = 'avatar-generate',
  ASSET_GENERATION = 'asset-generate',
  VIDEO_REFRAME = 'video-transform-reframe',
  VIDEO_UPSCALE = 'video-transform-upscale',
  IMAGE_REFRAME = 'image-transform-reframe',
  IMAGE_UPSCALE = 'image-transform-upscale',
  PROMPT_CREATION = 'prompt-create',
  PROMPT_ENHANCEMENT = 'prompt-enhance',
  PROMPT_REMIX = 'prompt-generate-remix',
  ARTICLE_ENHANCEMENT = 'article-enhance',
  ARTICLE_REMIX = 'article-remix',
  ARTICLE_VIRALITY_ANALYSIS = 'article-analyze-virality',
  ARTICLE_PROMPT_GENERATION = 'article-generate-prompt',
  POST_ENHANCEMENT = 'post-enhance',
  IMAGE_EVALUATION = 'image-evaluate',
  VIDEO_EVALUATION = 'video-evaluate',
  ARTICLE_EVALUATION = 'article-evaluate',
  CONTENT_EVALUATION = 'content-evaluate',
  MODELS_TRAINING = 'model-train',
  POST = 'content-publish',
  POST_GENERATION = 'post-generate',
  TWEET_REPLY = 'tweet-generate-reply',
  SOCIAL_INTEGRATION = 'integration-social',
  WEB = 'web',
  BOT_GENERATION = 'bot-generate',
  VOICE_GENERATION = 'voice-generate',
}

export enum ActivityKey {
  CREDITS_ADD = 'credits-add',
  CREDITS_REMOVE = 'credits-remove',
  CREDITS_REMOVE_ALL = 'credits-remove-all',
  CREDITS_RESET = 'credits-reset',
  IMAGE_PROCESSING = 'image-processing',
  IMAGE_GENERATED = 'image-generated',
  IMAGE_FAILED = 'image-failed',
  VIDEO_PROCESSING = 'video-processing',
  VIDEO_GENERATED = 'video-generated',
  VIDEO_COMPLETED = 'video-completed',
  VIDEO_FAILED = 'video-failed',
  VIDEO_SCHEDULED = 'video-scheduled',
  MUSIC_PROCESSING = 'music-processing',
  MUSIC_GENERATED = 'music-generated',
  MUSIC_FAILED = 'music-failed',
  MODELS_TRAINING_CREATED = 'model-training-created',
  MODELS_TRAINING_FAILED = 'model-training-failed',
  MODELS_TRAINING_COMPLETED = 'model-training-completed',
  SOCIAL_INTEGRATION_FAILED = 'integration-social-failed',
  SOCIAL_INTEGRATION_DISCONNECTED = 'integration-social-disconnected',
  POST_PROCESSING = 'post-processing',
  POST_GENERATED = 'post-generated',
  POST_FAILED = 'content-publish-failed',
  POST_SCHEDULED = 'content-publish-scheduled',
  POST_PUBLISHED = 'content-publish-published',
  POST_CREATED = 'content-created',
  ARTICLE_PROCESSING = 'article-processing',
  ARTICLE_GENERATED = 'article-generated',
  ARTICLE_FAILED = 'article-failed',
  VIDEO_REFRAME_PROCESSING = 'video-reframe-processing',
  VIDEO_REFRAME_COMPLETED = 'video-reframe-completed',
  VIDEO_REFRAME_FAILED = 'video-reframe-failed',
  VIDEO_UPSCALE_PROCESSING = 'video-upscale-processing',
  VIDEO_UPSCALE_COMPLETED = 'video-upscale-completed',
  VIDEO_UPSCALE_FAILED = 'video-upscale-failed',
  IMAGE_REFRAME_PROCESSING = 'image-reframe-processing',
  IMAGE_REFRAME_COMPLETED = 'image-reframe-completed',
  IMAGE_REFRAME_FAILED = 'image-reframe-failed',
  IMAGE_UPSCALE_PROCESSING = 'image-upscale-processing',
  IMAGE_UPSCALE_COMPLETED = 'image-upscale-completed',
  IMAGE_UPSCALE_FAILED = 'image-upscale-failed',
  PROMPT_ENHANCE_PROCESSING = 'prompt-enhance-processing',
  PROMPT_ENHANCE_COMPLETED = 'prompt-enhance-completed',
  PROMPT_ENHANCE_FAILED = 'prompt-enhance-failed',
  VOICE_PROCESSING = 'voice-processing',
  VOICE_GENERATED = 'voice-generated',
  VOICE_FAILED = 'voice-failed',
  PROMPT_REMIX_PROCESSING = 'prompt-remix-processing',
  PROMPT_REMIX_COMPLETED = 'prompt-remix-completed',
  PROMPT_REMIX_FAILED = 'prompt-remix-failed',
}

export enum ActivityStatus {
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export enum ActivityEntityModel {
  INGREDIENT = 'Ingredient',
  POST = 'Post',
  ARTICLE = 'Article',
}
