export enum AiActionType {
  ENHANCE_PROMPT = 'enhance-prompt',
  REWRITE = 'rewrite',
  SHORTEN = 'shorten',
  EXPAND = 'expand',
  TONE_ADJUST = 'tone-adjust',
  SEO_OPTIMIZE = 'seo-optimize',
  ADD_HASHTAGS = 'add-hashtags',
  HOOK_GENERATOR = 'hook-generator',
  ADAPT_PLATFORM = 'adapt-platform',
  GRAMMAR_CHECK = 'grammar-check',
  EXPLAIN_METRIC = 'explain-metric',
  SUGGEST_KEYWORDS = 'suggest-keywords',
  CONTENT_SUGGEST = 'content-suggest',
  ANALYTICS_INSIGHT = 'analytics-insight',
}

export const AI_ACTION_LABELS: Record<AiActionType, string> = {
  [AiActionType.ENHANCE_PROMPT]: 'Enhance',
  [AiActionType.REWRITE]: 'Rewrite',
  [AiActionType.SHORTEN]: 'Shorten',
  [AiActionType.EXPAND]: 'Expand',
  [AiActionType.TONE_ADJUST]: 'Adjust Tone',
  [AiActionType.SEO_OPTIMIZE]: 'SEO Optimize',
  [AiActionType.ADD_HASHTAGS]: 'Add Hashtags',
  [AiActionType.HOOK_GENERATOR]: 'Generate Hook',
  [AiActionType.ADAPT_PLATFORM]: 'Adapt Platform',
  [AiActionType.GRAMMAR_CHECK]: 'Grammar Check',
  [AiActionType.EXPLAIN_METRIC]: 'Explain Metric',
  [AiActionType.SUGGEST_KEYWORDS]: 'Suggest Keywords',
  [AiActionType.CONTENT_SUGGEST]: 'Suggest Content',
  [AiActionType.ANALYTICS_INSIGHT]: 'Analyze',
};

export const AI_ACTION_DESCRIPTIONS: Record<AiActionType, string> = {
  [AiActionType.ENHANCE_PROMPT]: 'Enhance prompt for AI generation',
  [AiActionType.REWRITE]: 'Rewrite with improved clarity',
  [AiActionType.SHORTEN]: 'Make text more concise',
  [AiActionType.EXPAND]: 'Add more detail and depth',
  [AiActionType.TONE_ADJUST]: 'Change the tone of the text',
  [AiActionType.SEO_OPTIMIZE]: 'Optimize for search engines',
  [AiActionType.ADD_HASHTAGS]: 'Generate relevant hashtags',
  [AiActionType.HOOK_GENERATOR]: 'Create attention-grabbing hooks',
  [AiActionType.ADAPT_PLATFORM]: 'Adapt for a specific platform',
  [AiActionType.GRAMMAR_CHECK]: 'Fix grammar and spelling',
  [AiActionType.EXPLAIN_METRIC]: 'Explain what this metric means',
  [AiActionType.SUGGEST_KEYWORDS]: 'Suggest relevant keywords',
  [AiActionType.CONTENT_SUGGEST]: 'Suggest content ideas',
  [AiActionType.ANALYTICS_INSIGHT]: 'Get actionable insights',
};
