export enum MetadataStyle {
  _3D_MODEL = '3d-model',
  ANALOG_FILM = 'analog-film',
  ANIME = 'anime',
  ASMR = 'asmr',
  AUTHENTIC = 'authentic',
  BOLD = 'bold',
  BRANDED = 'branded',
  CINEMATIC = 'cinematic',
  COMIC_BOOK = 'comic-book',
  COMMERCIAL = 'commercial',
  CORPORATE = 'corporate',
  CYBERPUNK = 'cyberpunk',
  DIGITAL_ART = 'digital-art',
  DOCUMENTARY = 'documentary',
  EDITORIAL = 'editorial',
  EDUCATIONAL = 'educational',
  FANTASY_ART = 'fantasy-art',
  FASHION = 'fashion',
  INFOGRAPHIC = 'infographic',
  ISOMETRIC = 'isometric',
  LIFESTYLE = 'lifestyle',
  LINE_ART = 'line-art',
  LOWPOLY = 'lowpoly',
  MEME = 'meme',
  METAL = 'metal',
  MINIMAL = 'minimal',
  MODELING_COMPOUND = 'modeling-compound',
  NEONPUNK = 'neonpunk',
  ORIGAMI = 'origami',
  PHOTOGRAPHIC = 'photographic',
  PIXEL_ART = 'pixel-art',
  PORTRAIT = 'portrait',
  PROMOTIONAL = 'promotional',
  SOCIAL_MEDIA = 'social-media',
  SPACE = 'space',
  STEAMPUNK = 'steampunk',
  SURREALISM = 'surrealism',
  THUMBNAIL = 'thumbnail',
  TRANSFORMATION = 'transformation',
  VINTAGE = 'vintage',
  WATERCOLOR = 'watercolor',
}

export enum MetadataExtension {
  JPEG = 'jpeg',
  JPG = 'jpg',
  PNG = 'png',
  GIF = 'gif',
  WEBP = 'webp',
  MP4 = 'mp4',
  WEBM = 'webm',
  MOV = 'mov',
  AVI = 'avi',
  MP3 = 'mp3',
  WAV = 'wav',
}
