export enum ModelKey {
  REPLICATE_FAST_FLUX_TRAINER = 'replicate/fast-flux-trainer',
  REPLICATE_GOOGLE_IMAGEN_3 = 'google/imagen-3',
  REPLICATE_GOOGLE_IMAGEN_3_FAST = 'google/imagen-3-fast',
  REPLICATE_GOOGLE_IMAGEN_4 = 'google/imagen-4',
  REPLICATE_GOOGLE_IMAGEN_4_FAST = 'google/imagen-4-fast',
  REPLICATE_GOOGLE_IMAGEN_4_ULTRA = 'google/imagen-4-ultra',
  REPLICATE_GOOGLE_NANO_BANANA = 'google/nano-banana',
  REPLICATE_GOOGLE_NANO_BANANA_PRO = 'google/nano-banana-pro',
  REPLICATE_GOOGLE_VEO_2 = 'google/veo-2',
  REPLICATE_GOOGLE_VEO_3 = 'google/veo-3',
  REPLICATE_GOOGLE_VEO_3_FAST = 'google/veo-3-fast',
  REPLICATE_GOOGLE_VEO_3_1 = 'google/veo-3.1',
  REPLICATE_GOOGLE_VEO_3_1_FAST = 'google/veo-3.1-fast',
  REPLICATE_IDEOGRAM_AI_IDEOGRAM_CHARACTER = 'ideogram-ai/ideogram-character',
  REPLICATE_IDEOGRAM_AI_IDEOGRAM_V3_BALANCED = 'ideogram-ai/ideogram-v3-balanced',
  REPLICATE_IDEOGRAM_AI_IDEOGRAM_V3_QUALITY = 'ideogram-ai/ideogram-v3-quality',
  REPLICATE_IDEOGRAM_AI_IDEOGRAM_V3_TURBO = 'ideogram-ai/ideogram-v3-turbo',
  REPLICATE_OPENAI_CLIP = 'openai/clip',
  REPLICATE_OPENAI_GPT_5_2 = 'openai/gpt-5.2',
  REPLICATE_OPENAI_GPT_IMAGE_1_5 = 'openai/gpt-image-1.5',
  REPLICATE_OPENAI_SORA_2 = 'openai/sora-2',
  REPLICATE_OPENAI_SORA_2_PRO = 'openai/sora-2-pro',
  REPLICATE_QWEN_QWEN_IMAGE = 'qwen/qwen-image',
  REPLICATE_RUNWAYML_GEN4_IMAGE_TURBO = 'runwayml/gen4-image-turbo',
  REPLICATE_BYTEDANCE_SEEDREAM_4 = 'bytedance/seedream-4',
  REPLICATE_BYTEDANCE_SEEDREAM_4_5 = 'bytedance/seedream-4.5',
  REPLICATE_BLACK_FOREST_LABS_FLUX_1_1_PRO = 'black-forest-labs/flux-1.1-pro',
  REPLICATE_BLACK_FOREST_LABS_FLUX_2_DEV = 'black-forest-labs/flux-2-dev',
  REPLICATE_BLACK_FOREST_LABS_FLUX_2_FLEX = 'black-forest-labs/flux-2-flex',
  REPLICATE_BLACK_FOREST_LABS_FLUX_2_PRO = 'black-forest-labs/flux-2-pro',
  REPLICATE_BLACK_FOREST_LABS_FLUX_KONTEXT_PRO = 'black-forest-labs/flux-kontext-pro',
  REPLICATE_BLACK_FOREST_LABS_FLUX_SCHNELL = 'black-forest-labs/flux-schnell',
  REPLICATE_LUMA_REFRAME_IMAGE = 'luma/reframe-image',
  REPLICATE_LUMA_REFRAME_VIDEO = 'luma/reframe-video',
  REPLICATE_TOPAZ_IMAGE_UPSCALE = 'topazlabs/image-upscale',
  REPLICATE_TOPAZ_VIDEO_UPSCALE = 'topazlabs/video-upscale',
  REPLICATE_KWAIVGI_KLING_V1_6_PRO = 'kwaivgi/kling-v1.6-pro',
  REPLICATE_KWAIVGI_KLING_V2_1 = 'kwaivgi/kling-v2.1',
  REPLICATE_KWAIVGI_KLING_V2_1_MASTER = 'kwaivgi/kling-v2.1-master',
  REPLICATE_KWAIVGI_KLING_V2_5_TURBO_PRO = 'kwaivgi/kling-v2.5-turbo-pro',
  REPLICATE_KWAIVGI_KLING_V3_VIDEO = 'kwaivgi/kling-v3-video',
  REPLICATE_KWAIVGI_KLING_V3_OMNI_VIDEO = 'kwaivgi/kling-v3-omni-video',
  REPLICATE_KWAIVGI_KLING_AVATAR_V2 = 'kwaivgi/kling-avatar-v2',
  REPLICATE_PRUNAAI_P_VIDEO = 'prunaai/p-video',
  REPLICATE_WAN_VIDEO_WAN_2_2_I2V_FAST = 'wan-video/wan-2.2-i2v-fast',
  REPLICATE_META_MUSICGEN = 'meta/musicgen',
  HEYGEN_AVATAR = 'heygen/avatar',
  REPLICATE_DEEPSEEK_AI_DEEPSEEK_R1 = 'deepseek-ai/deepseek-r1',
  REPLICATE_GOOGLE_GEMINI_2_5_FLASH = 'google/gemini-2.5-flash',
  REPLICATE_GOOGLE_GEMINI_3_PRO = 'google/gemini-3-pro',
  REPLICATE_META_LLAMA_3_1_405B_INSTRUCT = 'meta/meta-llama-3.1-405b-instruct',
  OPENROUTER_XAI_GROK_4_FAST = 'x-ai/grok-4-fast',
  OPENROUTER_XAI_GROK_4 = 'x-ai/grok-4',
  OPENROUTER_XAI_GROK_4_1_FAST = 'x-ai/grok-4.1-fast',
  KLINGAI_V2 = 'klingai-v2',
  LEONARDOAI = 'leonardoai',
  RUNWAYML = 'runwayml',
  SDXL = 'sdxl',

  // fal.ai models
  FAL_FLUX_DEV = 'fal-ai/flux/dev',
  FAL_FLUX_SCHNELL = 'fal-ai/flux/schnell',
  FAL_FLUX_PRO = 'fal-ai/flux-pro',
  FAL_KLING_VIDEO = 'fal-ai/kling-video',
  FAL_LUMA_DREAM_MACHINE = 'fal-ai/luma-dream-machine',
  FAL_RUNWAY_GEN3 = 'fal-ai/runway-gen3',
  FAL_SEEDANCE_2_0 = 'fal-ai/seedance-2.0',
  FAL_STABLE_VIDEO = 'fal-ai/stable-video-diffusion',
  FAL_WHISPER = 'fal-ai/whisper',
  FAL_ELEVEN_LABS_TTS = 'fal-ai/eleven-labs-tts',
  FAL_FACE_SWAP = 'fal-ai/face-swap',
  FAL_UPSCALER = 'fal-ai/clarity-upscaler',

  // HuggingFace models
  HF_SDXL = 'hf/stabilityai/stable-diffusion-xl-base-1.0',
  HF_FLUX_SCHNELL = 'hf/black-forest-labs/FLUX.1-schnell',
  HF_LLAMA_3_2_3B = 'hf/meta-llama/Llama-3.2-3B-Instruct',
  HF_MISTRAL_7B = 'hf/mistralai/Mistral-7B-Instruct-v0.3',
  HF_WHISPER_LARGE_V3 = 'hf/openai/whisper-large-v3',
  HF_MMS_TTS_ENG = 'hf/facebook/mms-tts-eng',
  HF_STABLE_VIDEO_DIFFUSION = 'hf/stabilityai/stable-video-diffusion-img2vid-xt',

  // Genfeed AI self-hosted models (ComfyUI on gpu.genfeed.ai)
  GENFEED_AI_FLUX_DEV = 'genfeed-ai/flux-dev',
  GENFEED_AI_FLUX_DEV_PULID = 'genfeed-ai/flux-dev-pulid',
  GENFEED_AI_Z_IMAGE_TURBO = 'genfeed-ai/z-image-turbo',
  GENFEED_AI_FLUX2_DEV = 'genfeed-ai/flux2-dev',
  GENFEED_AI_FLUX2_DEV_PULID = 'genfeed-ai/flux2-dev-pulid',
  GENFEED_AI_FLUX2_DEV_PULID_LORA = 'genfeed-ai/flux2-dev-pulid-lora',
  GENFEED_AI_FLUX2_DEV_PULID_UPSCALE = 'genfeed-ai/flux2-dev-pulid-upscale',
  GENFEED_AI_FLUX2_KLEIN = 'genfeed-ai/flux2-klein',
  GENFEED_AI_Z_IMAGE_TURBO_LORA = 'genfeed-ai/z-image-turbo-lora',
}

export enum ModelProvider {
  REPLICATE = 'replicate',
  FAL = 'fal',
  HUGGINGFACE = 'huggingface',
  GENFEED_AI = 'genfeed-ai',
}

export enum ModelCategory {
  TEXT = 'text',
  EMBEDDING = 'embedding',
  IMAGE = 'image',
  IMAGE_EDIT = 'image-edit',
  IMAGE_UPSCALE = 'image-upscale',
  VIDEO = 'video',
  VIDEO_EDIT = 'video-edit',
  VIDEO_UPSCALE = 'video-upscale',
  MUSIC = 'music',
  VOICE = 'voice',
}

export enum QualityTier {
  BASIC = 'basic',
  STANDARD = 'standard',
  HIGH = 'high',
  ULTRA = 'ultra',
}

export enum CostTier {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
}

export enum SpeedTier {
  FAST = 'fast',
  MEDIUM = 'medium',
  SLOW = 'slow',
}

export enum PricingType {
  FLAT = 'flat',
  PER_MEGAPIXEL = 'per-megapixel',
  PER_SECOND = 'per-second',
}
