export enum Platform {
  YOUTUBE = 'youtube',
  INSTAGRAM = 'instagram',
  TIKTOK = 'tiktok',
  FACEBOOK = 'facebook',
  GOOGLE_ADS = 'google_ads',
  TWITTER = 'twitter',
  LINKEDIN = 'linkedin',
  PINTEREST = 'pinterest',
  REDDIT = 'reddit',
  DISCORD = 'discord',
  TELEGRAM = 'telegram',
  TWITCH = 'twitch',
  MEDIUM = 'medium',
  THREADS = 'threads',
  FANVUE = 'fanvue',
  SLACK = 'slack',
  WORDPRESS = 'wordpress',
  SNAPCHAT = 'snapchat',
  WHATSAPP = 'whatsapp',
  MASTODON = 'mastodon',
  GHOST = 'ghost',
  SHOPIFY = 'shopify',
  BEEHIIV = 'beehiiv',
}
