export { Platform as TemplatePlatform } from './platform.enum';

export enum TemplateCategory {
  CAPTION = 'caption',
  VIDEO = 'video',
  IMAGE = 'image',
  ARTICLE = 'article',
  SCRIPT = 'script',
  EMAIL = 'email',
  SOCIAL_MEDIA = 'social-media',
  MARKETING = 'marketing',
  ECOMMERCE = 'ecommerce',
  EDUCATION = 'education',
  ENTERTAINMENT = 'entertainment',
  NEWS = 'news',
  PERSONAL_BRAND = 'personal-brand',
  CORPORATE = 'corporate',
  NONPROFIT = 'nonprofit',
  ARTICLE_GENERATION = 'article-generation',
  ARTICLE_EDIT = 'article-edit',
  ARTICLE_VIRALITY_ANALYSIS = 'article-virality-analysis',
  VIDEO_GENERATION = 'video-generation',
  VIDEO_CINEMATIC = 'video-cinematic',
  VIDEO_SOCIAL_MEDIA = 'video-social-media',
  VIDEO_PRODUCT_AD = 'video-product-ad',
  VIDEO_PODCAST = 'video-podcast',
  VIDEO_INFLUENCER = 'video-influencer',
  IMAGE_GENERATION = 'image-generation',
  IMAGE_PRODUCT_AD = 'image-product-ad',
  IMAGE_BANNER = 'image-banner',
  IMAGE_SUPER_MODEL = 'image-super-model',
  MUSIC_GENERATION = 'music-generation',
  CAPTION_GENERATION = 'caption-generation',
}

export enum TemplateDifficulty {
  BEGINNER = 'beginner',
  INTERMEDIATE = 'intermediate',
  ADVANCED = 'advanced',
}

export enum TemplateIndustry {
  TECHNOLOGY = 'technology',
  FINANCE = 'finance',
  HEALTHCARE = 'healthcare',
  RETAIL = 'retail',
  FOOD = 'food',
  FASHION = 'fashion',
  TRAVEL = 'travel',
  FITNESS = 'fitness',
  REAL_ESTATE = 'real-estate',
  AUTOMOTIVE = 'automotive',
  GENERAL = 'general',
}

export enum TemplateSortBy {
  POPULAR = 'popular',
  RECENT = 'recent',
  RATING = 'rating',
  USAGE = 'usage',
  NAME = 'name',
}

export enum VariableType {
  TEXT = 'text',
  NUMBER = 'number',
  BOOLEAN = 'boolean',
  SELECT = 'select',
  MULTISELECT = 'multiselect',
  COLOR = 'color',
  IMAGE = 'image',
  VIDEO = 'video',
  DATE = 'date',
  URL = 'url',
}

export enum SystemPromptKey {
  DEFAULT = 'system.default',
  IMAGE = 'system.image',
  VIDEO = 'system.video',
  MUSIC = 'system.music',
  ARTICLE = 'system.article',
  EVALUATION = 'system.evaluation',
  ENHANCEMENT = 'system.enhancement',
  VIRALITY = 'system.virality',
  TWEET = 'system.tweet',
  TWEET_REPLY = 'system.tweet-reply',
  IMAGE_PROMPT = 'system.image-prompt',
  TWITTER = 'system.twitter',
  TWITTER_CONTENT = 'system.twitter.content',
  TWITTER_TITLE = 'system.twitter.title',
  YOUTUBE = 'system.youtube',
  YOUTUBE_CONTENT = 'system.youtube.content',
  YOUTUBE_TITLE = 'system.youtube.title',
  INSTAGRAM = 'system.instagram',
  INSTAGRAM_CONTENT = 'system.instagram.content',
  INSTAGRAM_TITLE = 'system.instagram.title',
  LINKEDIN = 'system.linkedin',
  LINKEDIN_CONTENT = 'system.linkedin.content',
  LINKEDIN_TITLE = 'system.linkedin.title',
  TIKTOK = 'system.tiktok',
  TIKTOK_CONTENT = 'system.tiktok.content',
  TIKTOK_TITLE = 'system.tiktok.title',
  BRAND = 'system.brand',
  BRAND_CONTEXT = 'system.brand-context',
  BRAND_DESCRIPTION = 'system.brand-description',
  MODEL_IMAGE = 'system.model.image',
  MODEL_VIDEO = 'system.model.video',
  MODEL_MUSIC = 'system.model.music',
  MODEL_TRAINING = 'system.model.training',
  PRESET_TEXT = 'system.preset.text',
  PRESET_IMAGE = 'system.preset.image',
  PRESET_VIDEO = 'system.preset.video',
  PRESET_MUSIC = 'system.preset.music',
  STORYBOARD_SCRIPT = 'system.storyboard.script',
  X_ARTICLE = 'system.x-article',
  HOOK_GENERATOR = 'system.hook-generator',
}

export enum PromptTemplateKey {
  TEXT_DEFAULT = 'prompt.text.default',
  TEXT_ENHANCEMENT = 'prompt.text.enhancement',
  TEXT_ARTICLE = 'prompt.text.article',
  TEXT_TWEET = 'prompt.text.tweet',
  TEXT_TWEET_REPLY = 'prompt.text.tweet-reply',
  TEXT_IMAGE_PROMPT = 'prompt.text.image-prompt',
  TEXT_VIRALITY = 'prompt.text.virality',
  EVALUATION_VIDEO = 'prompt.evaluation.video',
  EVALUATION_IMAGE = 'prompt.evaluation.image',
  EVALUATION_ARTICLE = 'prompt.evaluation.article',
  EVALUATION_POST = 'prompt.evaluation.post',
  ARTICLE_GENERATE = 'prompt.article.generate',
  ARTICLE_EDIT = 'prompt.article.edit',
  ARTICLE_SEO = 'prompt.article.seo',
  ARTICLE_VIRALITY = 'prompt.article.virality',
  ARTICLE_TRANSCRIPT = 'prompt.article.transcript',
  ARTICLE_IMAGE_PROMPT = 'prompt.article.image-prompt',
  TWEET_GENERATION = 'prompt.tweet.generation',
  THREAD_GENERATION = 'prompt.thread.generation',
  THREAD_EXPAND = 'prompt.thread.expand',
  TWEET_REPLY = 'prompt.tweet.reply',
  POST_ENHANCEMENT = 'prompt.post.enhancement',
  REMIX = 'prompt.remix',
  ENHANCEMENT = 'prompt.enhancement',
  X_ARTICLE_GENERATE = 'prompt.x-article.generate',
  HOOK_VARIATIONS = 'prompt.hook.variations',
}

export enum ContentTemplateKey {
  VIDEO_DEFAULT = 'content.video.default',
  VIDEO_CINEMATIC = 'content.video.cinematic',
  VIDEO_SOCIAL = 'content.video.social',
  VIDEO_PRODUCT = 'content.video.product',
  VIDEO_PODCAST = 'content.video.podcast',
  VIDEO_INFLUENCER = 'content.video.influencer',
  IMAGE_DEFAULT = 'content.image.default',
  IMAGE_PRODUCT = 'content.image.product',
  IMAGE_BANNER = 'content.image.banner',
  IMAGE_SUPER_MODEL = 'content.image.super-model',
  IMAGE_SOCIAL_ILLUSTRATION = 'content.image.social-illustration',
  IMAGE_LOGO = 'content.image.logo',
  MUSIC_DEFAULT = 'content.music.default',
}
